---
apiVersion: v1
kind: Template
labels:
  app: ${NAME}-${INSTANCE}
  app.kubernetes.io/component: redis
  app.kubernetes.io/instance: ${INSTANCE}
  app.kubernetes.io/name: redis
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/part-of: ${NAME}-${INSTANCE}
  app.kubernetes.io/version: "6"
  template: ${NAME}-secret-template
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}-${INSTANCE}-secret
    stringData:
      username: default
      password: ${PASSWORD}
    type: kubernetes.io/basic-auth
parameters:
  - name: NAME
    description: The name of the application for labelling all artifacts.
    displayName: Application Name
    required: true
    value: redis
  - name: INSTANCE
    description: The name of this instance of the application
    displayName: Application Instance Name
    required: true
  - name: PASSWORD
    description: Password of the application database
    displayName: Application Database Password
    generate: expression
    from: "[a-zA-Z0-9]{32}"
    required: true
